
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: user
  pool: 5
  username: userAddrProd
  password: nani33378
  shost: localhost
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: DBNAME
  pool: 5
  username: usr
  password: paswd
  shost: localhost
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: DBNAME
  pool: 5
  username: usr
  password: paswd
  shost: localhost